version: '3.8'

services:
  app:
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # other environment variables...

  redis:
    image: redis
    ports:
      - "6379:6379"