version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    # other environment variables...

  redis:
    image: redis
    ports:
      - "6379:6379"