# Name of the workflow
name: MicroBlab application CI/CD pipeline

# Trigger the workflow on push or pull request to any branch
on: [push, pull_request]

jobs:
  # Job for building and testing the application
  build-and-test:
    runs-on: ubuntu-latest  # Specifies the type of runner to use (Ubuntu in this case)

    steps:
    - uses: actions/checkout@v2  # Checks out the repository code into the runner

    # Sets up Node.js environment, crucial for a Node.js/React project
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'  # Replace with your project's Node.js version

    # Install server (backend) dependencies
    - name: Install server dependencies
      run: npm install  # Runs npm install in the root directory to install server dependencies

    # Install client (frontend) dependencies
    - name: Install client dependencies
      run: |
        cd client
        npm install  # Navigates to the client directory and installs client dependencies

  #   # Optional: Run tests
  #   - name: Run tests
  #     run: npm test  # Runs the test script; customize or remove if not applicable

  #   # Build the client application for production
  #   - name: Build client for production
  #     run: |
  #       cd client
  #       npm run build  # Navigates to the client directory and builds the React application

  # # Define the deployment job here (if applicable)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test  # Ensures deployment starts only after successful build and test
  #   if: github.ref == 'refs/heads/main'  # Conditional to only deploy on changes to the main branch

  #   steps:
  #   - uses: actions/checkout@v2

  #   # Add deployment steps here
  #   # Example:
  #   # - name: Deploy to Production
  #   #   run: <deployment script or command>